### ISSUE TITLE
[Request] Import a group of members

### ISSUE THREAD

**Issue by sleepingdragoninn** [Oliver-makes-code/SwitchyKit#7]
There's lots of reasons someone might have pk members that don't represent someone who can play minecraft. It'd be great if you could specify a group to filter members down to when importing.

Knowing the current command hierachy and arg types, `/pk group [name]` and `/pk group [name] [link]` are probably the viable spots.

**Comment by Oliver-makes-code** [comment]
Poke me about this on discord in like, 12ish hours

**Comment by sleepingdragoninn** [comment]
sure!
